version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
    example-workflow:
      jobs:
        - cypress/run:
            install-command: npm install 
            include-branch-in-node-cache-key: false 
            install-browsers: false 
            package-manager: npm 
            cypress-command: npm run test 